<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.aihub</groupId>
        <artifactId>aihub-platform</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>aihub-admin</artifactId>
    <packaging>pom</packaging>
    <name>aihub-admin</name>

    <modules>
        <module>aihub-common</module>
        <module>aihub-dao</module>
        <module>aihub-service</module>
        <module>aihub-mq</module>
        <module>aihub-web</module>
    </modules>
</project>
